### ISSUE TITLE
make imagePoll options optional instead of required

### ISSUE THREAD

**Issue by ahmedkhitaby** [m3ntorship/pickify-posts#119]
### Updates
Update:
After some discussions and agreements, this will be always optional and any logic needed for certain post types will be handled on the front-end side.

### Story
- according to our design the option ``body`` in the image poll type is optional and in the other two types is required. if the user left the options empty at the image poll type and tries to create the post this leads to a ``400`` error.
![image](https://user-images.githubusercontent.com/52051312/124944999-11ef6e00-e00e-11eb-9e6e-f69f560350d5.png)

### Tasks
- [ ] make the option ``body`` in image poll type optional

**Comment by amroakmal** [comment]
Update:
After some discussions and agreements, this will be always optional and any logic needed for certain post types will be handled on the front-end side.
