### ISSUE TITLE
Create Docker image for mocking our Posts-API's specification.

### ISSUE THREAD

**Issue by saifaldin** [m3ntorship/pickify-posts#13]
### Story
Create a Docker image that implements spotlight/prism mocking our Posts-API's specification.
This is done to accomplish a more accessible way for other clients using our service ( e.g. Frontend of pickly ) to use mock data of agreed upon specifications, before the actual implementation.
The Dockerfile  with the mocked service should exist alongside the Dockerfile of our implemented service. That way all Posts' service related stuff are in the same repo.

### Prerequisites
- None

### Tasks
- [x] Add `Dockerfile-mock` to repo.
- [x] Add `docker-compose.yaml` to frontend repo.

### Acceptance criteria
- Frontend developers on Pickly's frontend should be able to use our mocked service with a simple `docker-compose up` command.

**Comment by amroakmal** [comment]
Should we close this issue because I think we achieved its goal or is there new task to be  made for this issue?
