### ISSUE TITLE
sorting posts and options

### ISSUE THREAD

**Issue by atwfk** [m3ntorship/pickify-posts#85]
### Story
- when we tested the api post creation and fetching the current posts we found that options are rendered reversely
![Screenshot from 2021-06-22 14-43-29](https://user-images.githubusercontent.com/52901348/122926590-51f4f680-d368-11eb-8c28-ac42b9692756.png)
- and posts are rendered in order of earliest date to latest date

### Acceptance criteria
- [ ] when the user create his post, he should see his post rendered at the top of the other posts based on the best UX
- [ ] the options should rendered in order of first option to last option

**Comment by amroakmal** [comment]
I think there's a conflict here, its written that we need to show posts from earliest date (old posts first) and increasing in date.
But at the same time, its written that we must show the user's most recent created post first which is contradicting the first thing.

So, does this  mean we need to give priorities to the posts? 
For example, we give user's own post a priority and they appear from most recent to older and other posts not created by the user should be viewed from oldest to newest?
